// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/habit-inversions/Gamified.tsx": () => import("../components/mockups/habit-inversions/Gamified.tsx"),
  "./components/mockups/habit-inversions/Terminal.tsx": () => import("../components/mockups/habit-inversions/Terminal.tsx"),
  "./components/mockups/habit-polish/Focused.tsx": () => import("../components/mockups/habit-polish/Focused.tsx"),
  "./components/mockups/habit-polish/Warmer.tsx": () => import("../components/mockups/habit-polish/Warmer.tsx")
};
